### ISSUE TITLE
[FE] 메인 홈 페이지

### ISSUE THREAD

**Issue by JongHoSke** [codestates-seb/seb45_main_014#4]
## 구현할 기능
- [x] 비 로그인 - 랜덤한 매장 정보 랜더링
- [x] 로그인 - 매장 정보 및 즐겨찾기 슬라이드 랜더링
- [x] PC 환경에서 즐겨찾기가 직관적으로 되어있음 좋겠다. 예를 들어 3개 단위로 오른쪽으로 넘길 수 있게 / 최종적으로 15개정도 보이면 될듯
- [x] 롤링배너

## 예상시간
- 6h

**Comment by YangSaekyul** [comment]
틀은 우선 완성했는데 로그인 여부 받아서 렌더링 정하는 거랑 데이터 받아오는 게 우선일듯 해서 보류하겠습니다!

**Comment by YangSaekyul** [comment]
API 생성 시 렌더링 방식 변경 후 종결 예정
